version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./operations/images/docker/postgresql/Dockerfile
    ports:
      - "5452:5432"
    volumes:
      - apiko_data:/var/lib/postgresql/data
    networks:
      - apiko_network

  api:
    build:
      context: .
      dockerfile: ./operations/images/docker/api/Dockerfile
    depends_on:
      - db
    ports:
      - "8090:8090"
      - "9239:9229"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - apiko_network

volumes:
  apiko_data:

networks:
  apiko_network:
