FROM postgres:13.3 AS postgresql

# POSTGRES_DB - used to define a different name for the default database that is created when the image is first started
ENV POSTGRES_DB apiko
ENV POSTGRES_USER apiko
ENV POSTGRES_PASSWORD apiko
